version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./data:/app/data:ro
    restart: unless-stopped

  dev:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - .:/app
      - ./data:/app/data:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  test:
    build: .
    environment:
      - ENV=test
    volumes:
      - .:/app
      - ./data:/app/data:ro
    command: >
      sh -c "
        echo 'Running comprehensive test suite...' &&
        pytest tests/ -v --cov=app --cov-report=term-missing --cov-report=html &&
        echo 'Running code quality checks...' &&
        ruff check app/ tests/ &&
        black --check app/ tests/ &&
        isort --check-only app/ tests/ &&
        echo 'All tests and quality checks passed!'
      "
    depends_on:
      - app

  benchmark:
    build: .
    environment:
      - ENV=benchmark
    volumes:
      - .:/app
      - ./data:/app/data:ro
    command: >
      sh -c "
        echo 'Starting benchmark tests...' &&
        pytest tests/ -v --benchmark-only --benchmark-sort=mean &&
        echo 'Benchmark tests completed!'
      "
    depends_on:
      - app

networks:
  default:
    name: feature-gateway-network