name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint (ruff)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Run ruff
        run: uv run ruff check app/ tests/

  format:
    name: Format check (black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Run black
        run: uv run black --check app/ tests/

  isort:
    name: Import sort check (isort)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Run isort
        run: uv run isort --check app/ tests/

  typecheck:
    name: Type check (mypy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Run mypy
        run: uv run mypy app/

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Run unit tests
        run: uv run pytest tests/ -v --cov=app --cov-report=term-missing

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Run integration tests
        run: uv run pytest tests/integration/ -v

  docker-test:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t feature-metadata-gateway .
      - name: Run Docker container test
        run: docker run --rm -e PYTHONUNBUFFERED=1 feature-metadata-gateway uv run pytest tests/ -v --cov=app --cov-report=term-missing

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install uv
        run: pip install uv
      - name: Sync dependencies
        run: uv sync
      - name: Bandit scan
        run: uv run bandit -r app/
      - name: Safety scan
        run: uv run safety scan

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [lint, format, isort, typecheck, unit-test, integration-test, docker-test, security]
    steps:
      - name: All checks passed
        run: echo "All CI checks completed successfully!"